<x-filament-panels::page>
    <div class="fi-tabs flex max-w-full gap-x-1 overflow-x-auto border-b border-gray-200 dark:border-gray-800 px-1">
        <button wire:click="switchTab('generator')" 
                type="button"
                class="fi-tabs-item relative flex items-center justify-center gap-x-2 px-3 py-2.5 text-sm font-semibold outline-none transition duration-150 {{ $activeTab === 'generator' ? 'text-emerald-600 dark:text-emerald-400 border-b-2 border-emerald-600 dark:border-emerald-400' : 'text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200' }}">
            <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/></svg>
            <span>Card Generator Engine</span>
        </button>

        <button wire:click="switchTab('folder')" 
                type="button"
                class="fi-tabs-item relative flex items-center justify-center gap-x-2 px-3 py-2.5 text-sm font-semibold outline-none transition duration-150 {{ $activeTab === 'folder' ? 'text-emerald-600 dark:text-emerald-400 border-b-2 border-emerald-600 dark:border-emerald-400' : 'text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200' }}">
            <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z"/></svg>
            <span>Cards Folder</span>
        </button>
    </div>

    @if($activeTab === 'generator')
        <div class="mt-4">
            <form wire:submit="generateCards" class="p-6 bg-white rounded-xl shadow-sm border border-gray-200 dark:bg-gray-900 dark:border-gray-800 space-y-6">
                {{ $this->form }}

                <div>
                    <button type="submit" 
                            class="inline-flex items-center justify-center gap-2 font-bold text-xs uppercase tracking-widest rounded-lg px-6 py-3 transition-all duration-150 transform active:scale-95 shadow-lg shadow-emerald-500/20 dark:shadow-emerald-500/10 cursor-pointer"
                            style="background-color: #059669 !important; color: #ffffff !important; border: 1px solid #047857 !important;">
                        <svg class="w-4 h-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.5" style="stroke: #ffffff !important;">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z" />
                        </svg>
                        <span style="color: #ffffff !important;">Generate Cards</span>
                    </button>
                </div>
            </form>
        </div>
    @else
        <div class="mt-4 bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden dark:bg-gray-900 dark:border-gray-800">
            <div class="p-4 bg-gray-50 border-b border-gray-200 dark:bg-gray-800/50 dark:border-gray-700 flex items-center justify-between">
                <h3 class="text-xs font-bold text-gray-700 dark:text-gray-300 uppercase tracking-wider">Storage Directory Reference Log Archive</h3>
                <span class="px-2.5 py-1 text-[10px] font-black uppercase tracking-wider bg-gray-200 text-gray-800 dark:bg-gray-700 dark:text-gray-100 rounded-md border border-gray-300 dark:border-gray-600 shadow-sm">
                    Total Batches: {{ count($archivedSheets) }}
                </span>
            </div>
            
            @if(count($archivedSheets) === 0)
                <div class="p-12 text-center text-gray-400 text-xs font-medium">
                    No historic document outputs found in storage directories.
                </div>
            @else
                <div class="overflow-x-auto">
                    <table class="w-full text-left border-collapse text-xs">
                        <thead>
                            <tr class="bg-gray-100/60 text-gray-500 dark:bg-gray-800/30 font-bold uppercase tracking-wider border-b border-gray-200 dark:border-gray-700">
                                <th class="p-3">Generated Document Item Description</th>
                                <th class="p-3">Target Project</th>
                                <th class="p-3 text-center">Enrolled Cards</th>
                                <th class="p-3">Generated By</th>
                                <th class="p-3 text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-gray-200 dark:divide-gray-800 dark:text-gray-200">
                            @foreach($archivedSheets as $sheet)
                                <tr class="hover:bg-gray-50/50 dark:hover:bg-gray-800/20">
                                    <td class="p-3 font-medium text-gray-900 dark:text-white inline-flex items-center gap-2">
                                        <svg class="w-4 h-4 text-rose-500 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"/></svg>
                                        {{ $sheet->filename }}
                                    </td>
                                    <td class="p-3 text-gray-500 dark:text-gray-400">{{ $sheet->project->name }}</td>
                                    <td class="p-3 text-center font-mono font-bold">{{ $sheet->total_cards }}</td>
                                    <td class="p-3 font-mono text-gray-500 dark:text-gray-400">{{ $sheet->generated_by }}</td>
                                    <td class="p-3 text-right space-x-2">
                                        <a href="{{ route('pdf.direct-download', ['filename' => basename($sheet->file_path)]) }}?stream=true" target="_blank" class="inline-flex items-center gap-1 font-bold text-blue-600 hover:underline dark:text-blue-400">View/Print</a>
                                        <a href="{{ route('pdf.direct-download', ['filename' => basename($sheet->file_path)]) }}" class="inline-flex items-center gap-1 font-bold text-emerald-600 hover:underline dark:text-emerald-400 pl-2">Download</a>
                                        <button wire:click="deleteSheet({{ $sheet->id }})" wire:confirm="Are you sure you want to delete this sheet permanently?" class="font-bold text-rose-600 hover:underline dark:text-rose-400 pl-2">Delete</button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            @endif
        </div>
    @endif

    @if($showPostGenerationModal)
        <div class="fixed inset-0 z-50 flex items-center justify-center p-4"
             style="background-color: rgba(15, 23, 42, 0.45); backdrop-filter: blur(6px); -webkit-backdrop-filter: blur(6px);"
             wire:click.self="$set('showPostGenerationModal', false)">
            
            <div class="relative bg-white dark:bg-gray-900 border border-gray-100 dark:border-gray-800"
                 style="max-width: 480px; width: 100%; border-radius: 28px; padding: 32px 32px 24px 32px; box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.15), 0 0 0 1px rgba(0,0,0,0.02); margin: auto;">
                
                {{-- Top Close Button --}}
                <button wire:click="$set('showPostGenerationModal', false)" 
                        type="button"
                        class="absolute transition-colors hover:opacity-75"
                        style="top: 20px; right: 20px; background: transparent; border: none; cursor: pointer; color: #94a3b8; padding: 4px;"
                        title="Close">
                    <svg style="width: 18px; height: 18px;" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.5">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>

                {{-- Header Row: Horizontal Icon + Title & Subtitle --}}
                <div style="display: flex; align-items: flex-start; gap: 16px;">
                    
                    {{-- Checkmark Icon with Celebration Burst Rays --}}
                    <div style="position: relative; flex-shrink: 0; width: 48px; height: 48px;">
                        {{-- Subtle burst rays --}}
                        <svg viewBox="0 0 48 48" style="position: absolute; top: -6px; left: -6px; width: 60px; height: 60px; pointer-events: none; opacity: 0.45;" fill="none">
                            <line x1="24" y1="2" x2="24" y2="7" stroke="#34d399" stroke-width="2.5" stroke-linecap="round" />
                            <line x1="8" y1="9" x2="12" y2="13" stroke="#34d399" stroke-width="2.5" stroke-linecap="round" />
                            <line x1="40" y1="9" x2="36" y2="13" stroke="#34d399" stroke-width="2.5" stroke-linecap="round" />
                        </svg>
                        <div style="width: 48px; height: 48px; border-radius: 50%; background-color: #d1fae5; display: flex; align-items: center; justify-content: center;">
                            <svg style="width: 24px; height: 24px; stroke: #059669;" fill="none" viewBox="0 0 24 24" stroke-width="3">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
                            </svg>
                        </div>
                    </div>

                    {{-- Title & Subtitle --}}
                    <div style="padding-right: 16px;">
                        <h3 style="font-size: 20px; font-weight: 800; color: #0f172a; margin: 0; line-height: 1.25; letter-spacing: -0.02em;">
                            Card Batch Ready
                        </h3>
                        <p style="font-size: 13px; color: #64748b; margin: 6px 0 0 0; line-height: 1.45;">
                            Beneficiary cards compiled and saved to your folder.
                        </p>
                    </div>
                </div>

                {{-- Document Info Box --}}
                <div style="background-color: #f8fafc; border: 1px solid #f1f5f9; border-radius: 18px; padding: 14px 16px; display: flex; align-items: center; justify-content: space-between; gap: 14px; margin-top: 22px;">
                    <div style="display: flex; align-items: center; gap: 14px; min-width: 0;">
                        <div style="width: 44px; height: 44px; border-radius: 12px; background-color: #d1fae5; display: flex; align-items: center; justify-content: center; flex-shrink: 0;">
                            <svg style="width: 22px; height: 22px; stroke: #047857;" fill="none" viewBox="0 0 24 24" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                            </svg>
                        </div>
                        <div style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
                            <div style="font-size: 14px; font-weight: 700; color: #0f172a; line-height: 1.25;">
                                Printable PDF Sheet
                            </div>
                            <div style="font-size: 12px; color: #64748b; margin-top: 2px; line-height: 1.25;">
                                A4 Batch Layout
                            </div>
                        </div>
                    </div>
                    
                    {{-- Ready Pill Badge --}}
                    <div style="display: inline-flex; align-items: center; gap: 6px; padding: 5px 12px; border-radius: 9999px; font-size: 12px; font-weight: 700; background-color: #dcfce7; color: #15803d; flex-shrink: 0;">
                        <svg style="width: 14px; height: 14px; fill: #15803d;" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                        </svg>
                        <span>Ready</span>
                    </div>
                </div>

                {{-- Action Buttons (Side-by-Side Pill Shapes) --}}
                <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 14px; margin-top: 20px;">
                    {{-- Preview & Print Button --}}
                    <a href="{{ $latestGeneratedFileUrl }}" 
                       target="_blank" 
                       wire:click="$set('showPostGenerationModal', false)" 
                       style="background-color: #059669 !important; color: #ffffff !important; border: 1px solid #047857 !important; border-radius: 9999px; height: 44px; display: inline-flex; align-items: center; justify-content: center; gap: 8px; font-weight: 700; font-size: 13px; text-decoration: none !important; box-shadow: 0 1px 3px rgba(0,0,0,0.08); cursor: pointer; transition: opacity 0.15s ease;"
                       onmouseover="this.style.opacity='0.95'" onmouseout="this.style.opacity='1'">
                        <svg style="width: 16px; height: 16px; stroke: #ffffff !important;" fill="none" viewBox="0 0 24 24" stroke-width="2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
                        </svg>
                        <span style="color: #ffffff !important; font-weight: 700 !important;">Preview & Print</span>
                    </a>
                    
                    {{-- Download PDF Button --}}
                    <a href="{{ $latestGeneratedFileDownloadUrl }}" 
                       wire:click="$set('showPostGenerationModal', false)" 
                       style="background-color: #ffffff !important; color: #0f172a !important; border: 1.5px solid #e2e8f0 !important; border-radius: 9999px; height: 44px; display: inline-flex; align-items: center; justify-content: center; gap: 8px; font-weight: 700; font-size: 13px; text-decoration: none !important; box-shadow: 0 1px 2px rgba(0,0,0,0.04); cursor: pointer; transition: background-color 0.15s ease;"
                       onmouseover="this.style.backgroundColor='#f8fafc'" onmouseout="this.style.backgroundColor='#ffffff'">
                        <svg style="width: 16px; height: 16px; stroke: #0f172a !important;" fill="none" viewBox="0 0 24 24" stroke-width="2.2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                        </svg>
                        <span style="color: #0f172a !important; font-weight: 700 !important;">Download PDF</span>
                    </a>
                </div>

                {{-- Bottom Folder Directory Link --}}
                <div style="display: flex; align-items: center; justify-content: space-between; margin-top: 24px; padding-top: 4px; color: #64748b; font-size: 13px; font-weight: 600; cursor: pointer; transition: color 0.15s ease;"
                     onmouseover="this.style.color='#0f172a'" onmouseout="this.style.color='#64748b'"
                     wire:click="dismissModalAndGoToFolder">
                    <div style="display: flex; align-items: center; gap: 10px;">
                        <svg style="width: 17px; height: 17px;" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" />
                        </svg>
                        <span>View all in Cards Folder</span>
                    </div>
                    <svg style="width: 15px; height: 15px; color: #94a3b8;" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M9 5l7 7-7 7" />
                    </svg>
                </div>
            </div>
        </div>
    @endif
</x-filament-panels::page>
