<x-filament-panels::page>
    <div class="fi-tabs flex max-w-full gap-x-1 overflow-x-auto border-b border-gray-200 dark:border-gray-800 px-1">
        <button wire:click="switchTab('generator')" 
                type="button"
                class="fi-tabs-item relative flex items-center justify-center gap-x-2 px-3 py-2.5 text-sm font-semibold outline-none transition duration-150 {{ $activeTab === 'generator' ? 'text-emerald-600 dark:text-emerald-400 border-b-2 border-emerald-600 dark:border-emerald-400' : 'text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200' }}">
            <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/></svg>
            <span>Card Generator Engine</span>
        </button>

        <button wire:click="switchTab('folder')" 
                type="button"
                class="fi-tabs-item relative flex items-center justify-center gap-x-2 px-3 py-2.5 text-sm font-semibold outline-none transition duration-150 {{ $activeTab === 'folder' ? 'text-emerald-600 dark:text-emerald-400 border-b-2 border-emerald-600 dark:border-emerald-400' : 'text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200' }}">
            <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z"/></svg>
            <span>Cards Folder</span>
        </button>
    </div>

    @if($activeTab === 'generator')
        <div class="mt-4">
            <form wire:submit="generateCards" class="p-6 bg-white rounded-xl shadow-sm border border-gray-200 dark:bg-gray-900 dark:border-gray-800 space-y-6">
                {{ $this->form }}

                <div>
                    <button type="submit" 
                            class="inline-flex items-center justify-center gap-2 font-bold text-xs uppercase tracking-widest rounded-lg px-6 py-3 transition-all duration-150 transform active:scale-95 shadow-lg shadow-emerald-500/20 dark:shadow-emerald-500/10 cursor-pointer"
                            style="background-color: #059669 !important; color: #ffffff !important; border: 1px solid #047857 !important;">
                        <svg class="w-4 h-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.5" style="stroke: #ffffff !important;">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z" />
                        </svg>
                        <span style="color: #ffffff !important;">Generate Cards</span>
                    </button>
                </div>
            </form>
        </div>
    @else
        <div class="mt-4 bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden dark:bg-gray-900 dark:border-gray-800">
            <div class="p-4 bg-gray-50 border-b border-gray-200 dark:bg-gray-800/50 dark:border-gray-700 flex items-center justify-between">
                <h3 class="text-xs font-bold text-gray-700 dark:text-gray-300 uppercase tracking-wider">Storage Directory Reference Log Archive</h3>
                <span class="px-2.5 py-1 text-[10px] font-black uppercase tracking-wider bg-gray-200 text-gray-800 dark:bg-gray-700 dark:text-gray-100 rounded-md border border-gray-300 dark:border-gray-600 shadow-sm">
                    Total Batches: {{ count($archivedSheets) }}
                </span>
            </div>
            
            @if(count($archivedSheets) === 0)
                <div class="p-12 text-center text-gray-400 text-xs font-medium">
                    No historic document outputs found in storage directories.
                </div>
            @else
                <div class="overflow-x-auto">
                    <table class="w-full text-left border-collapse text-xs">
                        <thead>
                            <tr class="bg-gray-100/60 text-gray-500 dark:bg-gray-800/30 font-bold uppercase tracking-wider border-b border-gray-200 dark:border-gray-700">
                                <th class="p-3">Generated Document Item Description</th>
                                <th class="p-3">Target Project</th>
                                <th class="p-3 text-center">Enrolled Cards</th>
                                <th class="p-3">Generated By</th>
                                <th class="p-3 text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-gray-200 dark:divide-gray-800 dark:text-gray-200">
                            @foreach($archivedSheets as $sheet)
                                <tr class="hover:bg-gray-50/50 dark:hover:bg-gray-800/20">
                                    <td class="p-3 font-medium text-gray-900 dark:text-white inline-flex items-center gap-2">
                                        <svg class="w-4 h-4 text-rose-500 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"/></svg>
                                        {{ $sheet->filename }}
                                    </td>
                                    <td class="p-3 text-gray-500 dark:text-gray-400">{{ $sheet->project->name }}</td>
                                    <td class="p-3 text-center font-mono font-bold">{{ $sheet->total_cards }}</td>
                                    <td class="p-3 font-mono text-gray-500 dark:text-gray-400">{{ $sheet->generated_by }}</td>
                                    <td class="p-3 text-right space-x-2">
                                        <a href="{{ route('pdf.direct-download', ['filename' => basename($sheet->file_path)]) }}?stream=true" target="_blank" class="inline-flex items-center gap-1 font-bold text-blue-600 hover:underline dark:text-blue-400">View/Print</a>
                                        <a href="{{ route('pdf.direct-download', ['filename' => basename($sheet->file_path)]) }}" class="inline-flex items-center gap-1 font-bold text-emerald-600 hover:underline dark:text-emerald-400 pl-2">Download</a>
                                        <button wire:click="deleteSheet({{ $sheet->id }})" wire:confirm="Are you sure you want to delete this sheet permanently?" class="font-bold text-rose-600 hover:underline dark:text-rose-400 pl-2">Delete</button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            @endif
        </div>
    @endif

    @if($showPostGenerationModal)
        <div class="fixed inset-0 bg-gray-950/60 backdrop-blur-lg flex items-center justify-center z-50 p-4 transition-all duration-300">
            <div class="bg-white dark:bg-gray-900 max-w-md w-full rounded-2xl shadow-2xl border border-gray-200 dark:border-gray-800 overflow-hidden transform scale-100">
                <div class="p-6 text-center border-b border-gray-100 dark:border-gray-800">
                    <div class="w-12 h-12 bg-emerald-100 dark:bg-emerald-950/50 text-emerald-600 dark:text-emerald-400 rounded-full flex items-center justify-center mx-auto mb-3">
                        <svg class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.5"><path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
                    </div>
                    <h3 class="text-base font-bold text-gray-900 dark:text-white">Card Batch Sheet Compiled Successfully!</h3>
                    <p class="text-xs text-gray-500 dark:text-gray-400 mt-1">The compiled PDF document has been safely saved to your operational system folder repository.</p>
                </div>
                
                <div class="p-4 bg-gray-50 dark:bg-gray-950 flex flex-col gap-2">
                    <a href="{{ $latestGeneratedFileUrl }}" target="_blank" wire:click="$set('showPostGenerationModal', false)" class="w-full inline-flex items-center justify-center py-2 px-4 rounded-xl text-xs font-bold uppercase tracking-wider text-white bg-blue-600 hover:bg-blue-700 transition-all text-center shadow-sm">
                        Print / Stream PDF Sheets Now
                    </a>
                    
                    <a href="{{ $latestGeneratedFileDownloadUrl }}" wire:click="$set('showPostGenerationModal', false)" class="w-full inline-flex items-center justify-center py-2 px-4 rounded-xl text-xs font-bold uppercase tracking-wider text-white bg-emerald-500 hover:bg-emerald-600 transition-all text-center shadow-sm">
                        Download File Globally Now
                    </a>
                    
                    <button wire:click="dismissModalAndGoToFolder" class="w-full inline-flex items-center justify-center py-2 px-4 rounded-xl text-xs font-bold uppercase tracking-wider text-gray-700 bg-white border border-gray-200 hover:bg-gray-50 dark:bg-gray-800 dark:text-gray-200 dark:border-gray-700 dark:hover:bg-gray-700/60 transition-all shadow-sm">
                        Go To Folder History Directory
                    </button>
                </div>

                <div class="p-3 text-center bg-gray-100 dark:bg-gray-900 border-t border-gray-100 dark:border-gray-800">
                    <button wire:click="$set('showPostGenerationModal', false)" class="text-xs font-bold text-gray-400 hover:text-gray-600 uppercase tracking-widest">Dismiss Dialog</button>
                </div>
            </div>
        </div>
    @endif
</x-filament-panels::page>